import React, { useState } from "react";
import { ArrowRight, Check, CheckCircle2, CircleAlert, FileText, History, MapPin, MessageSquareText, ShieldCheck, Sparkles, Truck, UserRoundCheck, X, ArrowUpRight } from "lucide-react";
import AgentInspector from "./AgentInspector";

export default function CaseWorkspace({ order, incident, traces, isInvestigating, onInvestigate, onDecision, isSubmitting, auditLedger }) {
  const [tab, setTab] = useState("case");
  const [notes, setNotes] = useState("");
  if (!order) return <section className="bg-white rounded-xl border border-slate-200 flex items-center justify-center min-h-[650px] text-slate-500">Select an order to review its fulfilment case.</section>;
  const score=Math.round((order.risk_score||0)*100);
  const pending=incident?.status === "PENDING_REVIEW";
  const recommendation=incident?.recommended_action || "Run risk analysis to generate an evidence-based recovery recommendation.";
  const voucher=incident?.proposed_payload?.proposed_voucher_brl;
  const slaDate=order.order_estimated_delivery_date ? new Date(order.order_estimated_delivery_date) : null;
  const slaRemaining=slaDate && !Number.isNaN(slaDate.valueOf()) ? `${Math.max(0, Math.round((slaDate-Date.now())/3600000))}h` : "Not available";
  const caseAudit=auditLedger.filter(a=>a.order_id===order.order_id && (!incident || a.incident_id===incident.incident_id));
  return <section className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden h-[calc(100vh-184px)] min-h-[650px] flex flex-col">
    <div className="px-6 pt-5 border-b border-slate-200">
      <div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="text-xs font-medium text-[#C4314B] bg-rose-50 px-2 py-1 rounded-md">Critical risk</span><span className="text-xs text-slate-500">Case RF-{order.order_id.slice(0,6).toUpperCase()}</span></div><h2 className="text-2xl font-semibold text-slate-900 mt-2">Order {order.order_id.slice(0,12).toUpperCase()}</h2><div className="flex flex-wrap items-center gap-2 mt-2 text-sm text-slate-600"><MapPin className="h-4 w-4"/>{order.seller_city}, {order.seller_state}<ArrowRight className="h-4 w-4 text-slate-400"/>{order.customer_city}, {order.customer_state}<span className="text-slate-300">|</span><span>{order.carrier_name}</span></div></div>
        <div className="grid grid-cols-3 divide-x divide-slate-200 border border-slate-200 rounded-lg min-w-[360px]"><div className="p-3"><p className="text-[11px] text-slate-500">Risk score</p><strong className="text-lg text-[#C4314B]">{score}%</strong></div><div className="p-3"><p className="text-[11px] text-slate-500">SLA remaining</p><strong className="text-lg text-slate-900">{slaRemaining}</strong></div><div className="p-3"><p className="text-[11px] text-slate-500">Order value</p><strong className="text-lg text-slate-900">R$ {order.price.toFixed(2)}</strong></div></div></div>
      <nav className="flex gap-6 mt-5">{[["case","Case overview"],["evidence","AI evidence & trace"],["audit","Audit history"]].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`pb-3 text-xs font-medium border-b-2 ${tab===v?"border-[#0F6CBD] text-[#0F6CBD]":"border-transparent text-slate-500"}`}>{l}{v==="evidence"&&traces.length>0?` (${traces.length})`:""}</button>)}</nav>
    </div>
    <div className="flex-1 overflow-auto bg-[#F8FAFC] p-6">
      {tab==="case" && <div className="grid xl:grid-cols-[1fr_360px] gap-5">
        <div className="space-y-5">
          <div className="bg-white border border-slate-200 rounded-xl p-5"><h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2"><CircleAlert className="h-4 w-4 text-[#C4314B]"/>Why this order is at risk</h3><div className="grid md:grid-cols-3 gap-3 mt-4">{[["Risk evidence",incident?.evidence_summary || "Analysis not run",incident?.primary_risk_factor || "No incident evidence yet"],["Transit route",`${order.seller_city}, ${order.seller_state}`,`${order.carrier_name} to ${order.customer_city}`],["SLA exposure",slaRemaining,order.order_estimated_delivery_date || "No estimated date"]].map(([a,b,c])=><div key={a} className="border border-slate-200 rounded-lg p-3"><p className="text-[11px] text-slate-500">{a}</p><p className="text-sm font-semibold text-slate-900 mt-1">{b}</p><p className="text-[11px] text-slate-500 mt-1">{c}</p></div>)}</div></div>
          <div className="bg-white border border-slate-200 rounded-xl p-5"><div className="flex justify-between"><h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#0F6CBD]"/>Recommended recovery plan</h3><span className="text-[11px] text-slate-500">AI generated · human controlled</span></div><p className="text-sm text-slate-600 mt-3">{recommendation}</p><div className="mt-4 divide-y divide-slate-100 border-y border-slate-100">{[[Truck,"Escalate carrier priority","Ready to submit"],[MessageSquareText,"Prepare proactive customer update","Draft only"],[FileText,voucher != null ? `Issue R$${Number(voucher).toFixed(2)} goodwill voucher` : "No voucher proposed","Requires approval"]].map(([Icon,a,b])=><div key={a} className="flex items-center gap-3 py-3"><div className="h-8 w-8 rounded-lg bg-blue-50 text-[#0F6CBD] flex items-center justify-center"><Icon className="h-4 w-4"/></div><span className="text-sm text-slate-800 flex-1">{a}</span><span className="text-[11px] bg-slate-100 text-slate-600 px-2 py-1 rounded">{b}</span></div>)}</div></div>
          <div className="bg-white border border-slate-200 rounded-xl p-5"><h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#1A7F37]"/>Policy check</h3><div className="grid md:grid-cols-3 gap-3 mt-4">{["Voucher is within R$25 cap","Customer message remains draft","Human approval required"].map(x=><div key={x} className="flex items-start gap-2 text-xs text-slate-700"><CheckCircle2 className="h-4 w-4 text-[#1A7F37] shrink-0"/>{x}</div>)}</div></div>
        </div>
        <aside className="bg-white border border-slate-200 rounded-xl p-5 h-fit sticky top-0"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-900">Decision</h3><span className="text-[11px] px-2 py-1 bg-amber-50 text-[#9A6700] rounded">{incident?.status?.replaceAll("_"," ") || "AWAITING REVIEW"}</span></div><p className="text-xs text-slate-500 mt-2">Review the evidence and policy boundary before approving.</p><label className="block text-xs font-medium text-slate-700 mt-5 mb-1.5">Decision notes</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows="4" placeholder="Add rationale for the audit trail…" className="w-full resize-none border border-slate-200 rounded-lg p-3 text-xs outline-none focus:border-[#0F6CBD]"/>
          {pending ? <div className="space-y-2 mt-4"><button disabled={isSubmitting} onClick={()=>onDecision(incident.incident_id,"APPROVED",notes,"Ops Specialist")} className="w-full bg-[#0F6CBD] hover:bg-[#0b5ca3] text-white rounded-lg py-2.5 text-sm font-semibold flex justify-center items-center gap-2 disabled:opacity-50"><Check className="h-4 w-4"/>Approve recovery plan</button><div className="grid grid-cols-2 gap-2"><button onClick={()=>onDecision(incident.incident_id,"REJECTED",notes,"Ops Specialist")} className="border border-slate-300 rounded-lg py-2 text-xs font-medium text-slate-700 flex justify-center gap-1"><X className="h-3.5 w-3.5"/>Reject</button><button disabled title="Planned feature" className="border border-slate-300 rounded-lg py-2 text-xs font-medium text-slate-400 flex justify-center gap-1 cursor-not-allowed"><ArrowUpRight className="h-3.5 w-3.5"/>Escalate · planned</button></div></div> : <button onClick={()=>onInvestigate(order.order_id)} disabled={isInvestigating} className="w-full mt-4 bg-[#0F6CBD] text-white rounded-lg py-2.5 text-sm font-semibold">{isInvestigating?"Analysing case…":"Run risk analysis"}</button>}
          <div className="mt-5 pt-4 border-t border-slate-100 flex gap-2 text-[11px] text-slate-500"><UserRoundCheck className="h-4 w-4"/><span>No action is executed until an authorised reviewer approves this plan.</span></div></aside>
      </div>}
      {tab==="evidence" && <AgentInspector selectedOrder={order} activeIncident={incident} traces={traces} isInvestigating={isInvestigating} onRunInvestigation={onInvestigate}/>} 
      {tab==="audit" && <div className="bg-white border border-slate-200 rounded-xl p-5"><h3 className="text-sm font-semibold flex items-center gap-2"><History className="h-4 w-4"/>Audit history</h3><div className="mt-4 divide-y divide-slate-100">{caseAudit.length?caseAudit.map(a=><div key={a.action_id} className="py-3 flex justify-between text-xs"><div><p className="font-medium text-slate-900">{a.action_type.replaceAll("_"," ")}</p><p className="text-slate-500 mt-1">{a.action_id} · {a.approved_by}</p></div><span className="text-[#1A7F37] font-semibold">{a.status}</span></div>):<p className="text-xs text-slate-500 py-8 text-center">No actions have been recorded for this case.</p>}</div></div>}
    </div>
  </section>;
}
